[server]
headless = true
enableXsrfProtection=false
enableCORS = false
[theme]
primaryColor = "#060606"
backgroundColor = "#101010"
secondaryBackgroundColor = "#960019"
textColor = "#FFFFFF"
font = "sans serif"
